### ISSUE TITLE
Exotic package support

### ISSUE THREAD

**Issue by jonblatho** [tmkn/packageanalyzer#616]
Would it be possible for this utility to support exotic packages, or am I missing something?

For example, when running `pkga tree --package git+ssh://git@github.com:tmkn/packageanalyzer.git` I get a "couldn't get package" error. Not sure if it's a matter of syntax or if it's simply not supported.

This utility looks really nice and I'd love to use it for some internal projects that are currently only in private Git repos, but this is holding me back for now.

**Comment by tmkn** [comment]
Hey, thanks for the input.
Currently this format is not supported.
The `--package` option only takes input in the form of `react@17.0.2` or `react` (which will default to the latest version), it will then go straight to NPM.

That said, it will also fail if the dependencies themselves in the `package.json` have this format.
I'll update the docs to be more clear about this.

While I don't see support for this format in the near future, eventually the packageanalyzer should support this format as it's a valid format to declare dependencies in the `package.json`.
